apiVersion: v1
kind: Secret
metadata:
  name: portal-secrets
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}