image:
  repository: devops-portal-backend
  tag: "local"
  pullPolicy: IfNotPresent

replicaCount: 1

env:
  appBaseUrl: "http://portal.local"
  postLoginRedirect: "/"
  oidcIssuer: "http://auth.portal.local/realms/devops-lab"
  oidcClientId: "portal"
  oidcRedirectUri: "http://portal.local/callback"
  oidcRequireAudience: "true"
  cookieSecure: "false"
  cookieSameSite: "lax"

secrets:
  oidcClientSecret: "CHANGE_ME"
  sessionSecret: "CHANGE_ME_RANDOM_LONG"

keycloakHostAlias:
  enabled: true
  ip: "10.109.239.81"  # ClusterIP of keycloak service
  port: 8000

ingress:
  enabled: true
  className: nginx
  portalHost: portal.test       # changed from portal.local
  apiHost: portal.test          # changed from portal.local
  keycloakHost: auth.portal.test # changed from auth.portal.local
  keycloakServiceName: keycloak
  keycloakServicePort: 80